# The run config defines the basic parameters for the backtest
[meta]
strategy_type = "simple_rsi_divergence"
timeframe = '1h'
symbol = 'ETHUSDT'

[strategy]
directions = ["long"]
use_regime = true
# bull_regime_classes = [1, 2]
# bear_regime_classes = [5, 6]
